// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace BasketApi.Infrastructure.FlatBuffers
{
    using global::System;
    using global::System.Collections.Generic;
    using global::Google.FlatBuffers;

    public struct BasketItemFB : IFlatbufferObject
    {
        private Table __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
        public static BasketItemFB GetRootAsBasketItemFB(ByteBuffer _bb) { return GetRootAsBasketItemFB(_bb, new BasketItemFB()); }
        public static BasketItemFB GetRootAsBasketItemFB(ByteBuffer _bb, BasketItemFB obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
        public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
        public BasketItemFB __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public string ProductId { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetProductIdBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
        public ArraySegment<byte>? GetProductIdBytes() { return __p.__vector_as_arraysegment(4); }
#endif
        public byte[] GetProductIdArray() { return __p.__vector_as_array<byte>(4); }
        public string ProductName { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetProductNameBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
        public ArraySegment<byte>? GetProductNameBytes() { return __p.__vector_as_arraysegment(6); }
#endif
        public byte[] GetProductNameArray() { return __p.__vector_as_array<byte>(6); }
        public double Price { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetDouble(o + __p.bb_pos) : (double)0.0; } }
        public int Quantity { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

        public static Offset<BasketApi.Infrastructure.FlatBuffers.BasketItemFB> CreateBasketItemFB(FlatBufferBuilder builder,
            StringOffset product_idOffset = default(StringOffset),
            StringOffset product_nameOffset = default(StringOffset),
            double price = 0.0,
            int quantity = 0) {
          builder.StartTable(4);
          BasketItemFB.AddPrice(builder, price);
          BasketItemFB.AddQuantity(builder, quantity);
          BasketItemFB.AddProductName(builder, product_nameOffset);
          BasketItemFB.AddProductId(builder, product_idOffset);
          return BasketItemFB.EndBasketItemFB(builder);
        }

        public static void StartBasketItemFB(FlatBufferBuilder builder) { builder.StartTable(4); }
        public static void AddProductId(FlatBufferBuilder builder, StringOffset productIdOffset) { builder.AddOffset(0, productIdOffset.Value, 0); }
        public static void AddProductName(FlatBufferBuilder builder, StringOffset productNameOffset) { builder.AddOffset(1, productNameOffset.Value, 0); }
        public static void AddPrice(FlatBufferBuilder builder, double price) { builder.AddDouble(2, price, 0.0); }
        public static void AddQuantity(FlatBufferBuilder builder, int quantity) { builder.AddInt(3, quantity, 0); }
        public static Offset<BasketApi.Infrastructure.FlatBuffers.BasketItemFB> EndBasketItemFB(FlatBufferBuilder builder) {
          int o = builder.EndTable();
          return new Offset<BasketApi.Infrastructure.FlatBuffers.BasketItemFB>(o);
        }
    }

    public struct BasketFB : IFlatbufferObject
    {
        private Table __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
        public static BasketFB GetRootAsBasketFB(ByteBuffer _bb) { return GetRootAsBasketFB(_bb, new BasketFB()); }
        public static BasketFB GetRootAsBasketFB(ByteBuffer _bb, BasketFB obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
        public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
        public BasketFB __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public string BuyerId { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetBuyerIdBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
        public ArraySegment<byte>? GetBuyerIdBytes() { return __p.__vector_as_arraysegment(4); }
#endif
        public byte[] GetBuyerIdArray() { return __p.__vector_as_array<byte>(4); }
        public BasketItemFB? Items(int j) { int o = __p.__offset(6); return o != 0 ? (BasketItemFB?)(new BasketItemFB()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
        public int ItemsLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }
        public double TotalPrice { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetDouble(o + __p.bb_pos) : (double)0.0; } }

        public static Offset<BasketApi.Infrastructure.FlatBuffers.BasketFB> CreateBasketFB(FlatBufferBuilder builder,
            StringOffset buyer_idOffset = default(StringOffset),
            VectorOffset itemsOffset = default(VectorOffset),
            double total_price = 0.0) {
          builder.StartTable(3);
          BasketFB.AddTotalPrice(builder, total_price);
          BasketFB.AddItems(builder, itemsOffset);
          BasketFB.AddBuyerId(builder, buyer_idOffset);
          return BasketFB.EndBasketFB(builder);
        }

        public static void StartBasketFB(FlatBufferBuilder builder) { builder.StartTable(3); }
        public static void AddBuyerId(FlatBufferBuilder builder, StringOffset buyerIdOffset) { builder.AddOffset(0, buyerIdOffset.Value, 0); }
        public static void AddItems(FlatBufferBuilder builder, VectorOffset itemsOffset) { builder.AddOffset(1, itemsOffset.Value, 0); }
        public static void AddTotalPrice(FlatBufferBuilder builder, double totalPrice) { builder.AddDouble(2, totalPrice, 0.0); }
        public static VectorOffset CreateItemsVector(FlatBufferBuilder builder, Offset<BasketApi.Infrastructure.FlatBuffers.BasketItemFB>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
        public static VectorOffset CreateItemsVectorBlock(FlatBufferBuilder builder, Offset<BasketApi.Infrastructure.FlatBuffers.BasketItemFB>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
        public static VectorOffset CreateItemsVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<BasketApi.Infrastructure.FlatBuffers.BasketItemFB>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
        public static VectorOffset CreateItemsVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<BasketApi.Infrastructure.FlatBuffers.BasketItemFB>>(dataPtr, sizeInBytes); return builder.EndVector(); }
        public static void StartItemsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
        public static Offset<BasketApi.Infrastructure.FlatBuffers.BasketFB> EndBasketFB(FlatBufferBuilder builder) {
          int o = builder.EndTable();
          return new Offset<BasketApi.Infrastructure.FlatBuffers.BasketFB>(o);
        }
        public static void FinishBasketFBBuffer(FlatBufferBuilder builder, Offset<BasketApi.Infrastructure.FlatBuffers.BasketFB> offset) { builder.Finish(offset.Value); }
        public static void FinishSizePrefixedBasketFBBuffer(FlatBufferBuilder builder, Offset<BasketApi.Infrastructure.FlatBuffers.BasketFB> offset) { builder.FinishSizePrefixed(offset.Value); }
    }
}
