global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "basket-api"
    static_configs:
      - targets: ["basketapi:8080"]
    metrics_path: "/metrics"
    scrape_interval: 10s

  - job_name: "vector"
    static_configs:
      - targets: ["vector:9090"]
    scrape_interval: 10s
